const fs = require('fs');
let lines = fs.readFileSync('module_dungeon.js', 'utf8').split('\n');

// Insert schedule code before line 900 (await setupDungeonFirebase())
const insertAtLine = 899; // 0-indexed → before line 900

const scheduleCode = [
  `    // ====== DUNGEON BOOKING SCHEDULE ======`,
  `    window.saveDungeonSchedule = async function() {`,
  `      if (!window.isUserAdmin || !window.isUserAdmin()) return;`,
  `      const openDate = document.getElementById('dqOpenDate')?.value || '';`,
  `      const openTime = document.getElementById('dqOpenTime')?.value || '';`,
  `      const closeTime = document.getElementById('dqCloseTime')?.value || '';`,
  `      if (!openDate || !openTime || !closeTime) return window.showToast('กรุณากรอกวันที่และเวลาให้ครบ', 'error');`,
  `      try {`,
  `        const scheduleRef = doc(window.db, 'guild_system', 'dungeon_schedule');`,
  `        await setDoc(scheduleRef, { openDate, openTime, closeTime, updatedAt: Date.now() });`,
  `        dungeonData._schedule = { openDate, openTime, closeTime };`,
  `        window.showToast('บันทึกตั้งค่าช่วงเวลาเปิดจองเรียบร้อยแล้ว', 'success');`,
  `        if (typeof renderDungeonScheduleStatus === 'function') renderDungeonScheduleStatus(true);`,
  `      } catch(e) { window.showToast('เกิดข้อผิดพลาด', 'error'); }`,
  `    };`,
  ``,
  `    window.clearDungeonSchedule = async function() {`,
  `      if (!window.isUserAdmin || !window.isUserAdmin()) return;`,
  `      try {`,
  `        const scheduleRef = doc(window.db, 'guild_system', 'dungeon_schedule');`,
  `        await setDoc(scheduleRef, { openDate: '', openTime: '', closeTime: '' });`,
  `        dungeonData._schedule = null;`,
  `        window.showToast('เปิดจองไม่จำกัดเวลาแล้ว', 'success');`,
  `        if (typeof renderDungeonScheduleStatus === 'function') renderDungeonScheduleStatus(window.isUserAdmin && window.isUserAdmin());`,
  `      } catch(e) { window.showToast('เกิดข้อผิดพลาด', 'error'); }`,
  `    };`,
  ``,
  `    function renderDungeonScheduleStatus(isAdmin) {`,
  `      const statusEl = document.getElementById('dqScheduleStatus');`,
  `      const bookBtn = document.getElementById('btnBookDungeon');`,
  `      if (!statusEl) return;`,
  `      const sched = dungeonData._schedule;`,
  `      if (!sched || !sched.openDate || !sched.openTime || !sched.closeTime) {`,
  `        statusEl.style.display = 'none';`,
  `        if (bookBtn) { bookBtn.disabled = false; bookBtn.style.opacity = '1'; }`,
  `        return;`,
  `      }`,
  `      const now = new Date();`,
  `      const nowDateStr = now.toLocaleDateString('en-CA', { timeZone: 'Asia/Bangkok' });`,
  `      const nowTimeStr = now.toLocaleTimeString('en-GB', { timeZone: 'Asia/Bangkok', hour: '2-digit', minute: '2-digit' });`,
  `      const isOpen = nowDateStr === sched.openDate && nowTimeStr >= sched.openTime && nowTimeStr <= sched.closeTime;`,
  `      if (isOpen) {`,
  `        statusEl.style.cssText = 'display:block;background:rgba(22,163,74,0.12);color:var(--ok);border:1px solid var(--ok);padding:10px 14px;border-radius:8px;font-size:13px;font-weight:600;margin-bottom:12px;';`,
  `        statusEl.textContent = '🟢 เปิดรับจองอยู่ (ถึง ' + sched.closeTime + ' น.)';`,
  `        if (bookBtn) { bookBtn.disabled = false; bookBtn.style.opacity = '1'; }`,
  `      } else {`,
  `        statusEl.style.cssText = 'display:block;background:rgba(239,68,68,0.08);color:var(--danger);border:1px solid var(--danger);padding:10px 14px;border-radius:8px;font-size:13px;font-weight:600;margin-bottom:12px;';`,
  `        const futureOpen = nowDateStr < sched.openDate || (nowDateStr === sched.openDate && nowTimeStr < sched.openTime);`,
  `        statusEl.textContent = futureOpen`,
  `          ? '🔒 จะเปิดจองวันที่ ' + sched.openDate + ' เวลา ' + sched.openTime + '–' + sched.closeTime + ' น.'`,
  `          : '🔒 ปิดรับการจองแล้ว';`,
  `        if (bookBtn && !isAdmin) { bookBtn.disabled = true; bookBtn.style.opacity = '0.5'; }`,
  `      }`,
  `    }`,
  `    window.renderDungeonScheduleStatus = renderDungeonScheduleStatus;`,
  ``,
  `    await (async function loadDungeonSchedule() {`,
  `      if (!window.db) return;`,
  `      try {`,
  `        const schedRef = doc(window.db, 'guild_system', 'dungeon_schedule');`,
  `        const snap = await getDoc(schedRef);`,
  `        if (snap.exists()) {`,
  `          const s = snap.data();`,
  `          if (s && (s.openDate || s.openTime)) {`,
  `            dungeonData._schedule = s;`,
  `            const od = document.getElementById('dqOpenDate');`,
  `            const ot = document.getElementById('dqOpenTime');`,
  `            const ct = document.getElementById('dqCloseTime');`,
  `            if (od) od.value = s.openDate || '';`,
  `            if (ot) ot.value = s.openTime || '';`,
  `            if (ct) ct.value = s.closeTime || '';`,
  `            renderDungeonScheduleStatus(window.isUserAdmin && window.isUserAdmin());`,
  `          }`,
  `        }`,
  `      } catch(e) { console.error('loadDungeonSchedule:', e); }`,
  `    })();`,
  ``,
];

lines.splice(insertAtLine, 0, ...scheduleCode);
fs.writeFileSync('module_dungeon.js', lines.join('\n'));
console.log('Inserted schedule code before line', insertAtLine + 1);
